name: Build RisingOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install git openjdk-17-jdk python3 curl wget repo -y

      - name: Init and Sync ROM Source
        run: |
          mkdir rising && cd rising
          repo init -u https://github.com/RisingOS-Revived/android -b qpr2 --git-lfs
          git clone https://github.com/ViaanROM/local_manifests .repo/local_manifests
          repo sync -c --no-clone-bundle --optimized-fetch --prune --force-sync -j$(nproc --all)

      - name: Setup Build Environment
        run: |
          cd rising
          source build/envsetup.sh
          lunch lineage_larry-user

      - name: Start Build
        run: |
          cd rising
          mka bacon -j$(nproc --all)

      - name: Upload ROM
        uses: actions/upload-artifact@v3
        with:
          name: RisingOS-ROM
          path: rising/out/target/product/larry/*.zip
